version: '1.9.7.{build}'

configuration: Release
platform: Any CPU
image:
- Visual Studio 2017
- Visual Studio 2019
- Ubuntu1804

shallow_clone: true

build: off
skip_tags: true

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

#dotnet_csproj:
#  patch: true
#  file: 'Source\*\*.csproj'
#  version: '{version}'
#  package_version: '{version}'
#  assembly_version: '{version}'
#  file_version: '{version}'
#  informational_version: '{version}'

for:

# Windows Build - Visual Studio 2017:
  -
    matrix:
      only:
        - image: Visual Studio 2017

    install:
    - cmd: choco install InnoSetup
    - cmd: SET PATH=C:\Program Files (x86)\Inno Setup 6;%PATH%

    before_build:
    - nuget restore -Verbosity quiet Source/Mosa.sln

    build:
      verbosity: minimal
      parallel: true
      project: Source/Mosa.sln
      publish_nuget: true

    after_build:
    - cmd: ISCC.exe Source/Inno-Setup-Script/Mosa-Installer.iss
    - ps: ./mosactl.ps1 unittest
#   - ps: ./mosactl.ps1 test

    build_script:

    test_script:
#    - cmd: ./mosactl.ps1 test

    after_test:

    nuget:
      project_feed: true

    test: off

    artifacts:
    - path: 'bin/MOSA-Installer.exe'
    - path: 'bin/mscorlib.dll'

    deploy:
      - provider: GitHub
        tag: Current
        release: MOSA Project - Development Build
        description: 'Build Version - v$(APPVEYOR_BUILD_VERSION) at $(APPVEYOR_REPO_COMMIT_TIMESTAMP)'
        auth_token:
          secure: HtzY0gh/s1gwDx89ZAqSdizGGNuQiyzXopLyFWhlpfC91/QvljGfNSS2L86hrl07            
        artifact: 'bin/MOSA-Installer.exe'
        draft: false
        prerelease: true
        force_update: true
        on:
          branch: master

      - provider: GitHub
        release: MOSA Project - Stable Build
        description: 'Build Version - v$(APPVEYOR_BUILD_VERSION) at $(APPVEYOR_REPO_COMMIT_TIMESTAMP)'
        auth_token:
          secure: HtzY0gh/s1gwDx89ZAqSdizGGNuQiyzXopLyFWhlpfC91/QvljGfNSS2L86hrl07            
        artifact: 'bin/MOSA-Installer.exe'
        draft: false
        prerelease: false
        force_update: true
        on:
          branch: stable

      - provider: NuGet
        server:                  
        api_key:
          secure: aTaYVizieVZLoxu3Cys6R6lAk3OvG5vtLp3ly4MBz6kwEr9I6HJfhFPNjeLpEa+Y
        skip_symbols: false
        symbol_server:           
        artifact: /.*\.nupkg/
		on:
          branch: stable

# Windows Build - Visual Studio 2019:
  -
    matrix:
      only:
        - image: Visual Studio 2019

    install:
    - cmd: choco install InnoSetup
    - cmd: SET PATH=C:\Program Files (x86)\Inno Setup 6;%PATH%

    before_build:
    - nuget restore -Verbosity quiet Source/Mosa.sln

    build:
      verbosity: minimal
      parallel: true
      project: Source/Mosa.sln
      publish_nuget: true

    after_build:
    - cmd: ISCC.exe Source/Inno-Setup-Script/Mosa-Installer.iss
#   - ps: ./mosactl.ps1 unittest
#   - ps: ./mosactl.ps1 test

    build_script:

    test_script:
#    - cmd: ./mosactl.ps1 test

    after_test:

    nuget:
      project_feed: true

    test: off

    assembly_info:
      patch: true
      file: AssemblyInfo.*
      assembly_version: "{version}"
      assembly_file_version: "{version}"
      assembly_informational_version: "{version}"

    artifacts:
    - path: 'bin/MOSA-Installer.exe'
    - path: 'bin/mscorlib.dll'

# Linux Build:
  -
    matrix:
      only:
        - image: Ubuntu1804

    install:
    - sh: docker pull mosaproject/mosa-docker-integration || docker pull mosaproject/mosa-docker-integration # with retry, if failed

    before_build:
    - echo test

    build: off

    build_script:
    - sh: echo UID "$UID"
    - sh: docker run --name MOSA -v $APPVEYOR_BUILD_FOLDER:/home/appveyor mosaproject/mosa-docker-integration /bin/bash -c "useradd -m -u $UID appveyor && su appveyor -- -c 'cd /home/appveyor && chmod +x mosactl && ./mosactl test && ./mosactl unittest'"
