Import:
#    .mosa-global.yml

Compiler:
    Architecture: x86	# Options: x86, x64, ArmARMv8A32
    BaseAddress: 0x00400000
	EnableStatistics : false
	TraceLevel : 0
	EnableMethodScanner: false # experimental option
	EmitInlinedMethods : false
	#OutputFile

SearchPaths:

Linker:
	EmitAllSymbols: false
	EmitStaticRelocations: false

CompilerDebug:
    DebugFile:
    MapFile:
    CompileTimeFile:

Optimizations:
    Basic: true
    SSA: true
    SCCP: true
    ValueNumbering: true
    LongExpansion: true
    EnableBitTracker: true
    Platform : true
    InlineMethods: true
    InlineMaximum: 12
	InlineAggressiveMaximum: 24
    InlineOnlyExplicit: true
    TwoPass: false

X86:
    InterruptMethodName: Mosa.Kernel.x86.IDT::ProcessInterrupt

AggressiveInline:				# Aggressively inline methods
	'Mosa.Runtime.Pointer::*'	

MethodDoNotInline:
	'Mosa.UnitTests::*'			# Don't inline the unit tests methods
