// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.IR
{
	/// <summary>
	/// BitCopyR4ToInt32
	/// </summary>
	/// <seealso cref="Mosa.Compiler.Framework.IR.BaseIRInstruction" />
	public sealed class BitCopyR4ToInt32 : BaseIRInstruction
	{
		public BitCopyR4ToInt32()
			: base(1, 1)
		{
		}
	}
}
