// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.IR
{
	/// <summary>
	/// BitCopyInt64ToR8
	/// </summary>
	/// <seealso cref="Mosa.Compiler.Framework.IR.BaseIRInstruction" />
	public sealed class BitCopyInt64ToR8 : BaseIRInstruction
	{
		public BitCopyInt64ToR8()
			: base(1, 1)
		{
		}
	}
}
