// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.IR
{
	/// <summary>
	/// ConvertInt32ToR8
	/// </summary>
	/// <seealso cref="Mosa.Compiler.Framework.IR.BaseIRInstruction" />
	public sealed class ConvertInt32ToR8 : BaseIRInstruction
	{
		public ConvertInt32ToR8()
			: base(1, 1)
		{
		}
	}
}
