// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.IR
{
	/// <summary>
	/// ConvertR4ToInt64
	/// </summary>
	/// <seealso cref="Mosa.Compiler.Framework.IR.BaseIRInstruction" />
	public sealed class ConvertR4ToInt64 : BaseIRInstruction
	{
		public ConvertR4ToInt64()
			: base(1, 1)
		{
		}
	}
}
