// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.IR
{
	/// <summary>
	/// ConvertInt32ToR4
	/// </summary>
	/// <seealso cref="Mosa.Compiler.Framework.IR.BaseIRInstruction" />
	public sealed class ConvertInt32ToR4 : BaseIRInstruction
	{
		public ConvertInt32ToR4()
			: base(1, 1)
		{
		}
	}
}
