// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.IR;

namespace Mosa.Compiler.Framework.Transform.Auto.IR.ConstantFolding
{
	/// <summary>
	/// ConvertInt32ToR4
	/// </summary>
	public sealed class ConvertInt32ToR4 : BaseTransformation
	{
		public ConvertInt32ToR4() : base(IRInstruction.ConvertInt32ToR4)
		{
		}

		public override bool Match(Context context, TransformContext transformContext)
		{
			if (!IsResolvedConstant(context.Operand1))
				return false;

			return true;
		}

		public override void Transform(Context context, TransformContext transformContext)
		{
			var result = context.Result;

			var t1 = context.Operand1;

			var e1 = transformContext.CreateConstant(ToR4(ToSignedInt32(t1)));

			context.SetInstruction(IRInstruction.MoveR4, result, e1);
		}
	}
}
