// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.IR;

namespace Mosa.Compiler.Framework.Transformation.Auto.IR.StrengthReduction
{
	/// <summary>
	/// RemUnsigned64ByPowerOfTwo
	/// </summary>
	public sealed class RemUnsigned64ByPowerOfTwo : BaseTransformation
	{
		public RemUnsigned64ByPowerOfTwo() : base(IRInstruction.RemUnsigned64)
		{
		}

		public override bool Match(Context context, TransformContext transformContext)
		{
			if (!IsResolvedConstant(context.Operand2))
				return false;

			if (!IsPowerOfTwo64(context.Operand2))
				return false;

			if (IsZero(context.Operand2))
				return false;

			return true;
		}

		public override void Transform(Context context, TransformContext transformContext)
		{
			var result = context.Result;

			var t1 = context.Operand1;
			var t2 = context.Operand2;

			var e1 = transformContext.CreateConstant(Sub32(ShiftLeft32(1u, GetPowerOfTwo(And32(ToInt32(t2), 63u))), 1u));

			context.SetInstruction(IRInstruction.LogicalAnd64, result, t1, e1);
		}
	}
}
