// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.IR;

namespace Mosa.Compiler.Framework.Transformation.Auto.IR.ConstantFolding
{
	/// <summary>
	/// GetHigh64
	/// </summary>
	public sealed class GetHigh64 : BaseTransformation
	{
		public GetHigh64() : base(IRInstruction.GetHigh64)
		{
		}

		public override bool Match(Context context, TransformContext transformContext)
		{
			if (!IsResolvedConstant(context.Operand1))
				return false;

			return true;
		}

		public override void Transform(Context context, TransformContext transformContext)
		{
			var result = context.Result;

			var t1 = context.Operand1;

			var e1 = transformContext.CreateConstant(ShiftRight32(ToInt32(t1), 32u));

			context.SetInstruction(IRInstruction.MoveInt32, result, e1);
		}
	}
}
