// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework;
using Mosa.Compiler.Framework.IR;
using Mosa.Compiler.Framework.Transformation;

namespace Mosa.Compiler.Framework.Transformation.IR2.ConstantFolding
{
	/// <summary>
	/// ConvertInt64ToFloatR8
	/// </summary>
	public sealed class ConvertInt64ToFloatR8 : BaseTransformation
	{
		public ConvertInt64ToFloatR8() : base(IRInstruction.ConvertInt64ToFloatR8)
		{
		}

		public override bool Match(Context context, TransformContext transformContext)
		{
			if (!IsResolvedConstant(context.Operand1))
				return false;

			return true;
		}

		public override void Transform(Context context, TransformContext transformContext)
		{
			var result = context.Result;

			var t1 = context.Operand1;

			var e1 = transformContext.CreateConstant(ToFloatR4(ToSignedInt64(t1)));

			context.SetInstruction(IRInstruction.MoveFloatR8, result, e1);
		}
	}
}
