// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework;
using Mosa.Compiler.Framework.IR;
using Mosa.Compiler.Framework.Transformation;

namespace Mosa.Compiler.Framework.Transformation.IR2.StrengthReduction
{
	/// <summary>
	/// ShiftRight64ZeroValue
	/// </summary>
	public sealed class ShiftRight64ZeroValue : BaseTransformation
	{
		public ShiftRight64ZeroValue() : base(IRInstruction.ShiftRight64)
		{
		}

		public override bool Match(Context context, TransformContext transformContext)
		{
			if (!context.Operand1.IsResolvedConstant)
				return false;

			if (context.Operand1.ConstantUnsigned64 != 0)
				return false;

			return true;
		}

		public override void Transform(Context context, TransformContext transformContext)
		{
			var result = context.Result;

			var t1 = context.Operand2;

			var c1 = transformContext.CreateConstant(0L);

			context.SetInstruction(IRInstruction.MoveInt64, result, c1);
		}
	}
}
