// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework;
using Mosa.Compiler.Framework.IR;
using Mosa.Compiler.Framework.Transformation;

namespace Mosa.Compiler.Framework.Transformation.IR2.StrengthReduction
{
	/// <summary>
	/// ShiftLeft64ByZero
	/// </summary>
	public sealed class ShiftLeft64ByZero : BaseTransformation
	{
		public ShiftLeft64ByZero() : base(IRInstruction.ShiftLeft64)
		{
		}

		public override bool Match(Context context, TransformContext transformContext)
		{
			if (!context.Operand2.IsResolvedConstant)
				return false;

			if (context.Operand2.ConstantUnsigned64 != 0)
				return false;

			return true;
		}

		public override void Transform(Context context, TransformContext transformContext)
		{
			var result = context.Result;

			var t1 = context.Operand1;

			context.SetInstruction(GetMove(result), result, t1);
		}
	}
}
