name: Builds

on:
  push:
  pull_request:

jobs:
  build-mswin:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Setup MSBuild
        uses: warrenbuckley/Setup-MSBuild@v1
      - name: Setup Nuget.exe
        uses: warrenbuckley/Setup-Nuget@v1
      - name: Restore nuget     
        run: dotnet restore Mosa.sln
        working-directory: Source
      - name: Build
        run: msbuild Source/Mosa.sln
      - name: List EXEs
        run: dir bin\*.exe
      - name: Package - Mosa.Tools.Package
        run: nuget pack Source\Mosa.Packages\Mosa.Tools.Package.nuspec -OutputDirectory bin -Version 2.0.0.0
      - name: Package - Mosa.Korlib
        run: dotnet pack Source/Mosa.Korlib/Mosa.Korlib.csproj -o bin -p:NuspecProperties="version=2.0.0.0"
      - name: Package - Mosa.Runtime
        run: dotnet pack Source/Mosa.Runtime/Mosa.Runtime.csproj -o bin -p:NuspecProperties="version=2.0.0.0"
      - name: Package - Mosa.Runtime.x86
        run: dotnet pack Source/Mosa.Runtime.x86/Mosa.Runtime.x86.csproj -o bin -p:NuspecProperties="version=2.0.0.0"
      - name: Package - Mosa.Kernel.x86
        run: dotnet pack Source/Mosa.Kernel.x86/Mosa.Kernel.x86.csproj -o bin -p:NuspecProperties="version=2.0.0.0"
      - name: Create Installer
        run: ISCC.exe /DMyAppVersion=2.0.0.0 Source/Inno-Setup-Script/Mosa-Installer.iss
      - name: Unit Tests - All Performance Optimizations
        run: bin\Mosa.Utility.UnitTests.exe -oMax -s Emulator.Display=false
      - name: Unit Tests - No Optimizations
        run: bin\Mosa.Utility.UnitTests.exe -oNone -s Emulator.Display=false
      - name: Unit Tests - Optimize for Fast Compile Time
        run: bin\Mosa.Utility.UnitTests.exe -oFast -s Emulator.Display=false
      - name: Unit Tests - Optimize for File Size
        run: bin\Mosa.Utility.UnitTests.exe -oFast -s Emulator.Display=false
      - name: Publish artifact
        uses: actions/upload-artifact@master
        with:
          name: nupkg
          path: finalpackages

  build-unix:
    name: Linux Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Update Package Respository
        run: sudo apt-get -y -o Acquire::Check-Valid-Until=false update
      - name: Install New Packages
        run: sudo apt-get install -y git wget qemu qemu-system qemu-system-x86
      - name: Restore nuget Packages
        run: dotnet restore Source/Mosa.sln
      - name: Build
        run: msbuild /verbosity:minimal Source/Mosa.sln
      - name: Unit Tests
        run: bin\Mosa.Utility.UnitTests.exe -settings tests\UnitTest.settings
