name: Unit Tests

on:
  push:
  pull_request:

jobs:
  build-mswin:
    name: Win - Unit Test
    runs-on: windows-latest

    strategy:
       matrix:
         levels: [-oMax, -oNone, -oFast, -oSpeed, -oSize, -o0, -o1, -o2, -o3, -o4, -o5, -o6, -o7, -o8, -o9]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Setup MSBuild
        uses: warrenbuckley/Setup-MSBuild@v1
      - name: Setup Nuget.exe
        uses: warrenbuckley/Setup-Nuget@v1
      - name: Set Build Version
        run: echo $BUILD_VERSION
        env:
          BUILD_VERSION: 2.0.0.0
      - name: Restore nuget     
        run: dotnet restore Mosa.sln
        working-directory: Source
      - name: Build
        run: msbuild Source/Mosa.sln
      - name: Unit Tests - ${{ matrix.level }}
        run: bin\Mosa.Utility.UnitTests.exe ${{ matrix.level }} -s Emulator.Display=false
