name: Builds

on:
  push:
  pull_request:

jobs:
  build-mswin:
    name: Windows Build
    runs-on: windows-latest

    strategy:
       matrix:
         levels: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Setup MSBuild
        uses: warrenbuckley/Setup-MSBuild@v1
      - name: Setup Nuget.exe
        uses: warrenbuckley/Setup-Nuget@v1
      - name: Set Build Version
        run: echo $BUILD_VERSION
        env:
          BUILD_VERSION: 2.0.0.0
      - name: Restore nuget     
        run: dotnet restore Mosa.sln
        working-directory: Source
      - name: Build
        run: msbuild Source/Mosa.sln
      - name: Unit Tests - ${{ matrix.level }}
        run: bin\Mosa.Utility.UnitTests.exe -o${{ matrix.level }} -s Emulator.Display=false
